apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-job.yml
  - pvc.yml
  - rbac.yml

generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: backup-scripts
    files:
      - scripts/backup.sh
      - scripts/start_backup.sql
      - scripts/stop_backup.sql
