apiVersion: v1
kind: ServiceAccount
metadata:
  name: backup
  namespace: database-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-exec
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec
subjects:
- kind: ServiceAccount
  name: backup
  namespace: database-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-exec
