resources:
  - init-job.yml

generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: db-init
    files:
      # users.csv is used as key
      - users.csv
      - init-db.sql
      - load.sh
