global:
  resolve_timeout: 5m
  smtp_smarthost: 192.168.50.254:25
  smtp_from: alerts-review@ocp4.example.com
  smtp_require_tls: false
receivers:
- name: default
- name: email-review
  email_configs:
    - to: ocp-review@example.com
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: default
  repeat_interval: 2m
  routes:
  - match:
      alertname: Watchdog
    receiver: default
  - match:
      severity: warning
    receiver: email-review
