apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: hello
    name: hello
  spec:
    replicas: 10
    selector:
      matchLabels:
        app: hello
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hello
      spec:
        containers:
        - image: quay.io/redhattraining/hello-world-nginx:v1.0
          name: hello-world-nginx
          resources:
            requests:
              cpu: 50m
              memory: 20Mi
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: hello
    name: hello
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hello
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      app: hello
    name: hello
  spec:
    host: ""
    port:
      targetPort: 8080
    to:
      kind: ""
      name: hello
      weight: null
  status:
    ingress: null
