apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: python-load
  name: python-load
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-load
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-load
    spec:
      containers:
      - image: quay.io/redhattraining/python-load:v0.1
        name: python-load
        resources: {}
status: {}
