apiVersion: v1
ind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-metering

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-metering
  namespace: openshift-metering
spec:
  targetNamespaces:
  - openshift-metering

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: lab-openshift-metering
  namespace: openshift-metering
spec:
  channel: "4.4"
  name: metering-ocp
  source: redhat-operators
  sourceNamespace: openshift-marketplace



